import Head from 'next/head'
import styles from '../styles/Home.module.css'
import bStyles from '../styles/Button.module.scss'
import {Button} from "../components/buttons/Button"
import {Radiobutton} from "../components/buttons/Radiobutton"
import {Checkbutton} from "../components/buttons/Checkbutton";
import {Test} from "../components/pages/Test"
import React from "react";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>basic-project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <button className={bStyles.button}>ОТВЕТИТЬ</button>
      </main>
    </div>
  )
}
